name: CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

      - name: Update SSM Config with Service Version
        run: |
          echo "Updating service version in the ssm..."

          SERVICE_VERSION="1.0.1" 
          SERVICE_NAME="rooster-demo-service"                         
          ENVIRONMENT="dev" 

          echo "Notifying with service version: $SERVICE_VERSION"
          echo "Full URL: https://watch-your-utilities.rooster-next-level.click/config/manager/updateServiceVersion/${SERVICE_NAME}/${ENVIRONMENT}/v1"
          echo 'Payload: {"serviceVersion": "'"$SERVICE_VERSION"'"}'

          curl --location 'https://watch-your-utilities.rooster-next-level.click/config/manager/updateServiceVersion/rooster-demo-service/dev/v1' \
              --header 'Content-Type: application/json' \
              --data '{
                "serviceVersion": "'"$SERVICE_VERSION"'"
            }'
